services:
  biblioteca-publica:
    extends:
      file: templates/biblioteca-publica.yml
      service: biblioteca-publica

  mysql:
    extends:
      file: templates/mysql.yml
      service: mysql

  minio:
    extends:
      file: templates/minio.yml
      service: minio
